alice/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :messages
  resources :send_loggers

  get 'sender/index'
  post 'sender/create'
  delete 'sender/delete'

  mount Sidekiq::Web => '/sidekiq'

  root 'sender#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alice/app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  enum status: %i[created sended recieved need_repeat repeated failed]
  after_initialize :set_default_status, if: :new_record?

  before_update :log_time, if: :status_changed?

  private

  def set_default_status
    self.status ||= :created
  end

  def log_time
    case status
    when 'sended'
      self.sended_at = Time.now
    when 'recieved'
      self.received_at = Time.now
    when 'repeated'
      self.repeated_at = Time.now
    end
  end
end

alice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

alice/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:txt, :sended_at, :received_at, :repeated_at, :state)
    end
end

alice/app/controllers/sender_controller.rb
# frozen_string_literal: true

require 'message_generator'

class SenderController < ApplicationController
  def index
    ss = Sidekiq::ScheduledSet.new
    @stats = ss.scan('SenderWorker').map(&:at)
  end

  def create
    interval = params['interval'].blank? ? rand(1...10) : params['interval'].to_i
    maxcount = params['maxcount'].blank? ? -1 : params['maxcount'].to_i

    mg = MessageGenerator.new
    message = Message.new(txt: mg.gen_string)

    respond_to do |format|
      if message.save
        SenderWorker.perform_in(interval.seconds, message.id, params['interval'].to_i, maxcount)
        format.html { redirect_to sender_index_path, notice: 'Job started successfully.' }
        format.json { render :index, status: :created }
      else
        format.html { render sender_index_path, notice: 'error' }
        format.json { render json: job.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    ss = Sidekiq::ScheduledSet.new
    ss.scan('SenderWorker').map(&:kill)

    respond_to do |format|
      if ss.scan('SenderWorker').any?
        format.html { render sender_index_path, notice: 'error' }
        format.json { render json: job.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to sender_index_path, notice: 'Job stopped successfully.' }
        format.json { render :index, status: :created }
      end
    end
  end
end

alice/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

alice/app/helpers/messages_helper.rb
module MessagesHelper
end

alice/app/helpers/send_loggers_helper.rb
module SendLoggersHelper
end

alice/app/helpers/sender_helper.rb
module SenderHelper
end

alice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

alice/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :txt %>
    <%= form.text_field :txt %>
  </div>

  <div class="field">
    <%= form.label :sended_at %>
    <%= form.datetime_select :sended_at %>
  </div>

  <div class="field">
    <%= form.label :received_at %>
    <%= form.datetime_select :received_at %>
  </div>

  <div class="field">
    <%= form.label :repeated_at %>
    <%= form.datetime_select :repeated_at %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

alice/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

alice/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Txt</th>
      <th>Sended at</th>
      <th>Received at</th>
      <th>Repeated at</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.txt %></td>
        <td><%= message.sended_at %></td>
        <td><%= message.received_at %></td>
        <td><%= message.repeated_at %></td>
        <td><%= message.status %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

alice/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

alice/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Txt:</strong>
  <%= @message.txt %>
</p>

<p>
  <strong>Sended at:</strong>
  <%= @message.sended_at %>
</p>

<p>
  <strong>Received at:</strong>
  <%= @message.received_at %>
</p>

<p>
  <strong>Repeated at:</strong>
  <%= @message.repeated_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @message.status %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

alice/app/views/sender/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sender</h1>

<%-if @stats.any? %>
<p><%= @stats %></p>
<%= link_to 'Stop', sender_delete_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<%-else%>
<%= form_with(url: sender_create_path) do |form| %>
  <div class="field">
    <%= form.label :interval %>
    <%= form.number_field :interval %>
  </div>

  <div class="field">
    <%= form.label :maxcount %>
    <%= form.number_field :maxcount %>
  </div>

  <div class="actions">
    <%= form.submit "Start" %>
  </div>
<% end %>
<%-end%>